### ISSUE TITLE
sacred vs. ipython 

### ISSUE THREAD

**Issue by matt32106** [gereleth/kaggle-telstra#1]
Have you tried using sacred directly from ipython? there is some weird error message when you try to execute `ex = Experiment...` from a notebook cell.
Is this why you did the experiment files as separate .py?

Thank you for sharing your code, this is really helpfull for a beginner kaggler like me :)
Happy competitions

**Comment by gereleth** [comment]
I remember trying to create an experiment in a notebook when I just started playing with Sacred, but that didn't work for me either.
I think it's best to first walk through all ml steps in a notebook (from loading data to running cv to generating a submission) and then create a separate experiment file based on this trial notebook. Reusable experiment files are nice =).

**Comment by matt32106** [comment]
Just my thoughts, thanks and good luck with competitions :)

**Comment by matt32106** [comment]
After some more investigation, it looks that if you use the magic `%%python` you can put your exps.py code in cells too:
```
%%python 
import os
...
from sacred import Experiment

rfex = Experiment('random_forest')

@rfex.config
def my_config():
    series = "RF"
```
